import os
from datetime import datetime

def generate_markdown_brief(work_item_id: int, title: str, summary: str, priority: str, deadline: str, action_items: list, missing_info: list) -> dict:
    """
    Generates a professional markdown brief summarizing a work item and saves it to a file.
    Returns status, content, and the filepath.
    """
    # Create briefs directory in the workspace if it doesn't exist
    briefs_dir = os.path.join(os.getcwd(), "briefs")
    os.makedirs(briefs_dir, exist_ok=True)
    
    filename = f"work_item_{work_item_id}_brief.md"
    filepath = os.path.join(briefs_dir, filename)
    
    # Render markdown content
    md_content = f"""# Work Item Brief: {title}

**Generated At**: {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}  
**Work Item ID**: {work_item_id}  
**Priority**: {priority.upper()}  
**Deadline**: {deadline or "None Specified"}

---

## Executive Summary
{summary}

"""

    if missing_info:
        md_content += "## Missing Information (Flagged)\n"
        for item in missing_info:
            md_content += f"- [ ] {item}\n"
        md_content += "\n"

    md_content += "## Action Execution Plan\n"
    for idx, item in enumerate(action_items, 1):
        status_symbol = "✓" if item.get("status") in ["COMPLETED", "EXECUTED"] else "⌛"
        md_content += f"### {idx}. {item.get('description')}\n"
        md_content += f"- **Status**: {item.get('status')} {status_symbol}\n"
        md_content += f"- **Automatable**: {'Yes' if item.get('automatable') else 'No'}\n"
        md_content += f"- **Route**: {item.get('action_type')}\n"
        md_content += f"- **Reason**: {item.get('reason')}\n"
        if item.get("output"):
            md_content += f"- **Output/Result**:\n  ```text\n  {item.get('output')}\n  ```\n"
        md_content += "\n"

    md_content += """---
*Generated by HEDAMO Agentic Ingestion System. Confidential business document.*
"""

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(md_content)
            
        return {
            "status": "SUCCESS",
            "filename": filename,
            "filepath": filepath,
            "content": md_content
        }
    except Exception as e:
        return {
            "status": "FAILED",
            "error": f"Failed to write markdown brief file: {str(e)}"
        }
